[project]
name = "thump"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "astropy>=7.2.0",
    "ipykernel>=7.1.0",
    "nbformat>=5.10.4",
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "polars>=1.37.1",
    "pyarrow>=23.0.0",
]
